import type { Metadata } from "next";
import "./global.css"

export const metadata: Metadata = {
  title: "Brook Hamilton's Portfolio Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
